apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: amazon
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo

    spec:
      containers:
        - name: k8s2
          image: adarsh011/amazon-abc-app:v5
          ports:
            - containerPort: 8080


          resources:
            requests:
              cpu: "256m"
              memory: "250Mi"

            limits:
              cpu: "550m"
              memory: "500Mi"

